export const API_ENDPOINTS = {
  PRESENCE: {
    ME: '/presence/me',
    USER: (userId: string) => `/presence/${userId}`,
    MULTIPLE: '/presence/multiple',
    ONLINE_ALL: '/presence/online/all',
    STATS: '/presence/stats',
  },
  AUTH: {
    REGISTER: '/auth/register',
    REGISTER_COMPANY: '/auth/register-company',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    TOUR_AGENTS: '/auth/tour-agents',
    CREATE_TOUR_AGENT: '/auth/tour-agents',
    CLAIM_ROLE: '/auth/claim-role',
    LOGOUT_ALL: '/auth/logout-all',
  },
  USERS: {
    LIST: '/users',
    ME: '/users/me',
    UPDATE_ME: '/users/me',
    DELETE_ME: '/users/me',
    BY_ID: (id: string) => `/users/${id}`,
    CREATE: '/users',
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
    UPDATE_ROLE: (id: string) => `/users/${id}/role`,
    REMOVE_ROLE: (id: string, role: string) => `/users/${id}/roles/${role}`,
    UPLOAD_AVATAR: (userId: string) => `/users/${userId}/avatar`,
  },
  TOURS: {
    LIST: '/tours',
    MY_TOURS: '/me/tours',
    CREATE: '/tours',
    GET: (id: string) => `/tours/${id}`,
    UPDATE: (id: string) => `/tours/${id}`,
    DELETE: (id: string) => `/tours/${id}`,
    UPLOAD_IMAGE: (id: string) => `/tours/${id}/images`,
    DELETE_IMAGE: (imageId: string) => `/media/${imageId}`,
  },
  COMPANIES: {
    LIST: '/companies',
    GET: (id: string) => `/companies/${id}`,
    MY_COMPANY: '/companies/my',
    UPDATE: (id: string) => `/companies/${id}`,
    DELETE: (id: string) => `/companies/${id}`,
    TOURS: (id: string) => `/companies/${id}/tours`,
    PHOTOS: (id: string) => `/companies/${id}/photos`,
    DELETE_PHOTO: (id: string, photoId: string) => `/companies/${id}/photos/${photoId}`,
    UPLOAD_LOGO: (id: string) => `/companies/${id}/logo`,
  },
  GUIDES: {
    LIST: '/guides',
    MY: '/guides/my',
    GET: (id: string) => `/guides/${id}`,
    UPDATE: (id: string) => `/guides/${id}`,
    DELETE: (id: string) => `/guides/${id}`,
    PHOTOS: (id: string) => `/guides/${id}/photos`,
    DELETE_PHOTO: (id: string, photoId: string) => `/guides/${id}/photos/${photoId}`,
    UPLOAD_AVATAR: (id: string) => `/guides/${id}/avatar`,
  },
  DRIVERS: {
    LIST: '/drivers',
    MY: '/drivers/my',
    GET: (id: string) => `/drivers/${id}`,
    UPDATE: (id: string) => `/drivers/${id}`,
    DELETE: (id: string) => `/drivers/${id}`,
    PHOTOS: (id: string) => `/drivers/${id}/photos`,
    DELETE_PHOTO: (id: string, photoId: string) => `/drivers/${id}/photos/${photoId}`,
    UPLOAD_AVATAR: (id: string) => `/drivers/${id}/avatar`,
  },
  LOCATIONS: {
    LIST: '/locations',
    GET: (id: string) => `/locations/${id}`,
    SEARCH: '/locations/search',
    CREATE: '/locations',
    UPDATE: (id: string) => `/locations/${id}`,
    DELETE: (id: string) => `/locations/${id}`,
  },
  BOOKINGS: {
    LIST: '/bookings',
    CREATE: '/bookings',
    GET: (id: string) => `/bookings/${id}`,
    UPDATE: (id: string) => `/bookings/${id}`,
    CANCEL: (id: string) => `/bookings/${id}/cancel`,
  },
  INQUIRIES: {
    LIST: '/inquiries',
    RECEIVED: '/inquiries/received',
    CREATE: '/inquiries',
    GET: (id: string) => `/inquiries/${id}`,
    RESPOND: (id: string) => `/inquiries/${id}/respond`,
  },
  SEARCH: {
    MAIN: '/search',
    LOCATIONS: '/search/locations',
    LOCATION_STATS: (id: string) => `/search/locations/${id}/stats`,
  },
  CHATS: {
    LIST: '/chats',
    DIRECT: '/chats/direct',
    GET: (id: string) => `/chats/${id}`,
    MESSAGES: (chatId: string) => `/chats/${chatId}/messages`,
    SEND_MESSAGE: (chatId: string) => `/chats/${chatId}/messages`,
    MARK_READ: (chatId: string) => `/chats/${chatId}/read`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    DELETE: (id: string) => `/notifications/${id}`,
  },
  REVIEWS: {
    LIST: '/reviews',
    STATS: '/reviews/stats',
    CREATE: '/reviews',
    MY_REVIEWS: '/reviews/my',
    CHECK: '/reviews/check',
    UPDATE: (id: string) => `/reviews/${id}`,
    DELETE: (id: string) => `/reviews/${id}`,
  },
  MEDIA: {
    GET: (entityType: string, entityId: string) => `/media/${entityType}/${entityId}`,
    UPLOAD: (entityType: string, entityId: string) => `/media/${entityType}/${entityId}`,
    BATCH_UPLOAD: (entityType: string, entityId: string) =>
      `/media/${entityType}/${entityId}/batch`,
    DELETE: (id: string) => `/media/${id}`,
  },
  HEALTH: {
    BASIC: '/health',
    DETAILED: '/health/detailed',
    METRICS: '/health/metrics',
    READY: '/health/ready',
    LIVE: '/health/live',
  },
  ADMIN: {
    AUDIT_LOGS: '/admin/audit-logs',
    RESTORE_USER: (id: string) => `/admin/users/${id}/restore`,
  },
} as const;
