export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  COMPANY_REGISTER: '/register-company',
  VERIFY_EMAIL: '/verify-email',
  VERIFY_EMAIL_PENDING: '/verify-email-pending',
  ACCEPT_INVITATION: '/accept-invitation',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  PROFILE: '/dashboard/profile',
  SETTINGS: '/dashboard/settings',
  CREATE_AGENT: '/dashboard/create-agent',
  COMPANY_MANAGEMENT: '/dashboard/company',
  DRIVER_DASHBOARD: '/dashboard/driver',
  GUIDE_DASHBOARD: '/dashboard/guide',
  BECOME_PARTNER: '/dashboard/become-partner',
  REVIEWS: '/dashboard/reviews',
  FAVORITES: '/dashboard/favorites',
  BOOKINGS: {
    ROOT: '/dashboard/bookings',
    RECEIVED: '/dashboard/bookings/received',
    DETAIL: (id: string) => `/dashboard/bookings/${id}`,
    CONFIRMATION: (id: string) => `/dashboard/bookings/${id}/confirmation`,
  },
  ANALYTICS: '/dashboard/analytics',
  AI_STUDIO: '/dashboard/ai-studio',
  OPERATIONS: {
    ROOT: '/dashboard/operations',
    AGENTS: '/dashboard/operations/agents',
    TOURS: '/dashboard/operations/tours',
  },
  INQUIRIES: {
    ROOT: '/dashboard/inquiries',
    SENT: '/dashboard/inquiries/sent',
    RECEIVED: '/dashboard/inquiries/received',
    CREATE: '/dashboard/inquiries/create',
    DETAILS: (id: string) => `/dashboard/inquiries/${id}`,
  },
  EXPLORE: {
    ROOT: '/explore',
    TOURS: '/explore/tours',
    COMPANIES: '/explore/companies',
    COMPANIES_COMPARE: '/explore/companies/compare',
    GUIDES: '/explore/guides',
    GUIDES_COMPARE: '/explore/guides/compare',
    DRIVERS: '/explore/drivers',
    DRIVERS_COMPARE: '/explore/drivers/compare',
  },
  TOURS: {
    LIST: '/explore/tours',
    DETAILS: (id: string) => `/explore/tours/${id}`,
    MY_TOURS: '/my-tours',
    CREATE: '/dashboard/tours/create',
    EDIT: (id: string) => `/explore/tours/${id}/edit`,
  },
  COMPANIES: {
    LIST: '/companies',
    DETAILS: (id: string) => `/companies/${id}`,
  },
  GUIDES: {
    LIST: '/guides',
    DETAILS: (id: string) => `/guides/${id}`,
  },
  DRIVERS: {
    LIST: '/drivers',
    DETAILS: (id: string) => `/drivers/${id}`,
  },
  ADMIN: {
    ROOT: '/dashboard/admin',
    DASHBOARD: '/dashboard/admin',
    USERS: '/dashboard/admin/users',
    LOCATIONS: '/dashboard/admin/locations',
    AI_TEMPLATES: '/dashboard/admin/ai-templates',
  },
  BLOG: {
    LIST: '/blog',
    POST: (slug: string) => `/blog/${slug}`,
    DASHBOARD: '/dashboard/blog',
    CREATE: '/dashboard/blog/create',
    EDIT: (id: string) => `/dashboard/blog/${id}/edit`,
  },
  LEGAL: {
    PRIVACY: '/legal/privacy',
    TERMS: '/legal/terms',
    COOKIES: '/legal/cookies',
  },
} as const;
