export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  COMPANY_REGISTER: '/register-company',
  VERIFY_EMAIL: '/verify-email',
  VERIFY_EMAIL_PENDING: '/verify-email-pending',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  PROFILE: '/dashboard/profile',
  SETTINGS: '/dashboard/settings',
  CREATE_AGENT: '/dashboard/create-agent',
  COMPANY_MANAGEMENT: '/dashboard/company',
  DRIVER_DASHBOARD: '/dashboard/driver',
  GUIDE_DASHBOARD: '/dashboard/guide',
  BECOME_PARTNER: '/dashboard/become-partner',
  REVIEWS: '/dashboard/reviews',
  OPERATIONS: {
    ROOT: '/dashboard/operations',
    AGENTS: '/dashboard/operations/agents',
    TOURS: '/dashboard/operations/tours',
  },
  INQUIRIES: {
    ROOT: '/dashboard/inquiries',
    SENT: '/dashboard/inquiries/sent',
    RECEIVED: '/dashboard/inquiries/received',
    CREATE: '/dashboard/inquiries/create',
    DETAILS: (id: string) => `/dashboard/inquiries/${id}`,
  },
  EXPLORE: {
    ROOT: '/explore',
    TOURS: '/explore/tours',
    COMPANIES: '/explore/companies',
    GUIDES: '/explore/guides',
    DRIVERS: '/explore/drivers',
  },
  TOURS: {
    LIST: '/explore/tours',
    DETAILS: (id: string) => `/explore/tours/${id}`,
    MY_TOURS: '/my-tours',
    CREATE: '/dashboard/tours/create',
    EDIT: (id: string) => `/explore/tours/${id}/edit`,
  },
  COMPANIES: {
    LIST: '/companies',
    DETAILS: (id: string) => `/companies/${id}`,
  },
  GUIDES: {
    LIST: '/guides',
    DETAILS: (id: string) => `/guides/${id}`,
  },
  DRIVERS: {
    LIST: '/drivers',
    DETAILS: (id: string) => `/drivers/${id}`,
  },
  ADMIN: {
    ROOT: '/dashboard/admin',
    DASHBOARD: '/dashboard/admin',
    USERS: '/dashboard/admin/users',
    LOCATIONS: '/dashboard/admin/locations',
  },
} as const;
